---
name: Build wheels

on: push

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-22.04, windows-2022, macos-11]

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.13.1
              env:
                  CIBW_ARCHS_MACOS: x86_64 arm64

            - uses: actions/upload-artifact@v3
              with:
                  path: ./wheelhouse/*.whl
